# Section: Federated Learning

# Lesson: Introducing Federated Learning

Federated Learning is a technique for training Deep Learning models on data to which you do not have access. Basically:

Federated Learning: Instead of bringing all the data to one machine and training a model, we bring the model to the data, train it locally, and merely upload "model updates" to a central server.

Use Cases:

    - app company (Texting prediction app)
    - predictive maintenance (automobiles / industrial engines)
    - wearable medical devices
    - ad blockers / autotomplete in browsers (Firefox/Brave)
    
Challenge Description: data is distributed amongst sources but we cannot aggregated it because of:

    - privacy concerns: legal, user discomfort, competitive dynamics
    - engineering: the bandwidth/storage requirements of aggregating the larger dataset

# Lesson: Introducing / Installing PySyft

In order to perform Federated Learning, we need to be able to use Deep Learning techniques on remote machines. This will require a new set of tools. Specifically, we will use an extensin of PyTorch called PySyft.

### Install PySyft

The easiest way to install the required libraries is with [Conda](https://docs.conda.io/projects/conda/en/latest/user-guide/overview.html). Create a new environment, then install the dependencies in that environment. In your terminal:

```bash
conda create -n pysyft python=3
conda activate pysyft # some older version of conda require "source activate pysyft" instead.
conda install jupyter notebook
pip install syft
pip install numpy
```

If you have any errors relating to zstd - run the following (if everything above installed fine then skip this step):

```
pip install --upgrade --force-reinstall zstd
```

and then retry installing syft (pip install syft).

If you are using Windows, I suggest installing [Anaconda and using the Anaconda Prompt](https://docs.anaconda.com/anaconda/user-guide/getting-started/) to work from the command line. 

With this environment activated and in the repo directory, launch Jupyter Notebook:

```bash
jupyter notebook
```

and re-open this notebook on the new Jupyter server.



In [2]:
!pip install syft
!pip install numpy

     |████████████████████████████████| 215kB 3.3MB/s 
     |████████████████████████████████| 450kB 49.5MB/s 
     |████████████████████████████████| 256kB 47.3MB/s 
     |████████████████████████████████| 389kB 53.4MB/s 
     |████████████████████████████████| 71kB 33.2MB/s 
     |████████████████████████████████| 1.4MB 50.3MB/s 
     |████████████████████████████████| 204kB 60.3MB/s 
     |████████████████████████████████| 51kB 26.8MB/s 
     |████████████████████████████████| 276kB 48.3MB/s 
     |████████████████████████████████| 122kB 53.5MB/s 
  Stored in directory: /root/.cache/pip/wheels/ad/9a/f4/3105b5209674ac77fcca7fede95184c62a95df0196888e0e76
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built zstd pyyaml
  Found existing installation: msgpack 0.5.6
    Uninstalling msgpack-0.5.6:
      Successfully uninstalled msgpack-0.5.6
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
   

In [0]:
import torch as th

In [0]:
x = th.tensor([1,2,3,4,5])
x

tensor([1, 2, 3, 4, 5])

In [0]:
y = x + x

In [0]:
print(y)

tensor([ 2,  4,  6,  8, 10])


In [0]:
import syft as sy

W0625 18:28:46.406823 140348963522432 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0-rc1.so'
W0625 18:28:46.426077 140348963522432 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)  # this line of code create an instance of th with its backend APIs modified with Syft functions

In [0]:
th.tensor([1,2,3,4,5]) # notice that Torch functionalities still behave the same

tensor([1, 2, 3, 4, 5])

# Lesson: Basic Remote Execution in PySyft

## PySyft => Remote PyTorch

The essence of Federated Learning is the ability to train models in parallel on a wide number of machines. Thus, we need the ability to tell remote machines to execute the operations required for Deep Learning.

Thus, instead of using Torch tensors - we're now going to work with **pointers** to tensors. Let me show you what I mean. First, let's create a "pretend" machine owned by a "pretend" person - we'll call him Bob.

In [0]:
bob = sy.VirtualWorker(hook, id="bob") # creates a virtual worker (a simulaion to interface to Bob machines)

In [0]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5])

In [0]:
x_ptr =  x.send(bob) # send this data to bob

In [0]:
bob._objects

{66334714076: tensor([1, 2, 3, 4, 5])}

In [0]:
x_ptr

(Wrapper)>[PointerTensor | me:48348495859 -> bob:66334714076]

In [0]:
x.location

<VirtualWorker id:bob #objects:1>

In [0]:
x.id_at_location

66334714076

In [0]:
x.id

48348495859

In [0]:
x.owner

<VirtualWorker id:me #objects:0>

In [0]:
hook.local_worker

<VirtualWorker id:me #objects:0>

In [0]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [0]:
bob._objects

{}

# Project: Experience with Remote Tensors

In this project, I want you to .send() and .get() a tensor to TWO workers by calling .send(bob,alice). This will first require the creation of another VirtualWorker called alice.

In [0]:
# create a second Virtual worker and call it Alice


In [0]:
# 1 - create some data (a tensor)
# 2- send the data to bob and alice


In [0]:
# notice what does the send fucntion on two workers return; a multi-pointer
x_ptr

In [0]:
# what does .child on the pointer object return?
# what does .child.child on the pointer object return? 

In [0]:
# try the .get() on the pointer


In [0]:
# try the .get(sum_results=True) on your pointer


# Lesson: Introducing Remote Arithmetic

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(bob)

In [0]:
x # a pointer to a remote tensor located at bob

(Wrapper)>[PointerTensor | me:96502616908 -> bob:83999397113]

In [0]:
y # a pointer to another remote tensor located at bob

(Wrapper)>[PointerTensor | me:35900922850 -> bob:59092289169]

In [0]:
z = x + y # treat those tensors (i.e., x and y) as local tensors, but they are actually executed remotely
z

(Wrapper)>[PointerTensor | me:12996980457 -> bob:54222168809]

In [0]:
z = z.get()
z

tensor([2, 3, 4, 5, 6])

In [0]:
z = th.add(x,y) # we can also use Torch operation on these tensors to be executed remotely
z

(Wrapper)>[PointerTensor | me:28437210120 -> bob:28437210120]

In [0]:
z = z.get() # yup! same results!
z

tensor([2, 3, 4, 5, 6])

In [0]:
x = th.tensor([1.,2,3,4,5], requires_grad=True).send(bob)
y = th.tensor([1.,1,1,1,1], requires_grad=True).send(bob)

In [0]:
z = (x + y).sum()
z = z.get()
z

tensor(20., requires_grad=True)

In [0]:
z.backward() 

tensor(20., requires_grad=True)

In [0]:
x = x.get()

In [0]:
x

tensor([1., 2., 3., 4., 5.], requires_grad=True)

In [0]:
x.grad

tensor([1., 1., 1., 1., 1.])

# Project: Learn a Simple Linear Model

In this project, I'd like for you to create a simple linear model which will solve for the following dataset below. You should use only Variables and .backward() to do so (no optimizers or nn.Modules). 

Furthermore, you must do so with both the data and the model being located on Bob's machine.

In [0]:
import torch as th
import syft as sy

hook = sy.TorchHook(th)  
bob = sy.VirtualWorker(hook, id="bob")

bob

W0702 21:46:59.193202 140155880675200 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0702 21:46:59.213361 140155880675200 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



<VirtualWorker id:bob #objects:0>

In [0]:
# create some toy data for our model
input_data = th.tensor([[1.,1],[0.5,1],[1,0],[0,0]], requires_grad=True).send(bob)
output_data = th.tensor([[1.],[1],[0],[0]], requires_grad=True).send(bob)

In [0]:
# create some linear weights and send them to bob
weights = th.tensor([[0.01],[0.01]], requires_grad = True).send(bob)

In [0]:
# create a linear model and train it on Bob's machine
# remember how to create a linear model? No? :( 
# Here's the main steps:
#    1- find a prediction
#    2- calcualte the loss (a mean square loss)
#    3- backpropogate using the backword() function
#    4- DO NOT forget to clear your gradients after updating the weights
#    weights.data.sub_(weights.grad * lr)

prediction = input_data.mm(weights)
prediction

(Wrapper)>[PointerTensor | me:15127782505 -> bob:52047116384]

In [0]:
lr = 0.1

for i in range(10):
  prediction = input_data.mm(weights)
  loss = ((prediction - output_data)**2).mean()
  loss.backward()#calculating gradients
  weights.data.sub_(weights.grad * lr)
  weights.grad *= 0

  print(loss.get().data)

tensor(0.0461)
tensor(0.0420)
tensor(0.0386)
tensor(0.0357)
tensor(0.0332)
tensor(0.0309)
tensor(0.0288)
tensor(0.0269)
tensor(0.0252)
tensor(0.0236)


# Lesson: Garbage Collection and Common Errors


In [0]:
bob = bob.clear_objects() # clear the contents of a remote object

In [0]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

{85910937763: tensor([1, 2, 3, 4, 5])}

In [0]:
del x  # delete the pointer to the remote object

In [0]:
bob._objects

{}

In [0]:
x.child.garbage_collect_data  # True by default

True

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

{84615314564: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [0]:
bob._objects

{}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x

(Wrapper)>[PointerTensor | me:39795892651 -> bob:12911623213]

In [0]:
bob._objects

{12911623213: tensor([1, 2, 3, 4, 5])}

In [0]:
x = "asdf"

In [0]:
bob._objects  # some error from Jupyter is casuing this to appear!

{12911623213: tensor([1, 2, 3, 4, 5])}

In [0]:
del x

In [0]:
bob._objects

{12911623213: tensor([1, 2, 3, 4, 5])}

In [0]:
bob = bob.clear_objects() # erase force 
bob._objects

{}

In [0]:
for i in range(1000):
    x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects # notice that there is only a single tensor in bob

{15601760445: tensor([1, 2, 3, 4, 5])}

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1])

In [0]:
z = x + y

TensorsNotCollocatedException: You tried to call a method involving two tensors where one tensor is actually locatedon another machine (is a PointerTensor). Call .get() on the PointerTensor or .send(bob) on the other tensor.

Tensor A: [PointerTensor | me:46419059800 -> bob:14412738960]
Tensor B: tensor([1, 1, 1, 1, 1])

In [0]:
alice = sy.VirtualWorker(hook, id="alice")
x = th.tensor([1,2,3,4,5]).send(bob)
y = th.tensor([1,1,1,1,1]).send(alice)

In [0]:
z = x + y

TensorsNotCollocatedException: ignored

# Lesson: Toy Federated Learning

Let's start by training a toy model the centralized way. This is about a simple as models get. We first need:

- a toy dataset
- a model
- some basic training logic for training a model to fit the data.

In [0]:
from torch import nn, optim

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target = th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# A Toy Model
model = nn.Linear(2,1)

In [0]:
opt = optim.SGD(params=model.parameters(), lr=0.1)

In [0]:
def train(iterations=10):
    for iter in range(iterations):
        opt.zero_grad()

        pred = model(data)

        loss = ((pred - target)**2).sum()

        loss.backward()

        opt.step()

        print(loss.data)
        
train()

tensor(1.4499)
tensor(0.7783)
tensor(0.5051)
tensor(0.3378)
tensor(0.2280)
tensor(0.1549)
tensor(0.1061)
tensor(0.0732)
tensor(0.0509)
tensor(0.0357)


In [3]:
# nothing was federated up to this point!

import torch as th
import syft as sy

hook = sy.TorchHook(th)  

bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")



W0702 23:02:18.293117 140195150854016 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0702 23:02:18.309613 140195150854016 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
# create local datasets at Bob and Alice
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)

In [7]:
datasets = [(data_bob, target_bob), (data_alice, target_alice)]
datasets

[((Wrapper)>[PointerTensor | me:14654636648 -> bob:56761390447],
  (Wrapper)>[PointerTensor | me:39434493617 -> bob:2608897113]),
 ((Wrapper)>[PointerTensor | me:99691064346 -> alice:31218402319],
  (Wrapper)>[PointerTensor | me:40771605067 -> alice:16115437368])]

In [0]:
def train(iterations=1):

    model = nn.Linear(2,1)
    opt = optim.SGD(params=model.parameters(), lr=0.1)
    
    for iter in range(iterations):

        for _data, _target in datasets:

            # send model to the data
            model = model.send(_data.location)

            # do training on the remote machine
            opt.zero_grad()
            pred = model(_data)
            loss = ((pred - _target)**2).mean()
            loss.backward()
            opt.step()

            # get smarter model back
            model = model.get()

            print(loss.get())

In [11]:
train()

tensor(1.5503, requires_grad=True)
tensor(0.1058, requires_grad=True)


# Lesson: Advanced Remote Execution Tools

In the last section we trained a toy model using Federated Learning. We did this by calling .send() and .get() on our model, sending it to the location of training data, updating it, and then bringing it back. However, at the end of the example we realized that we needed to go a bit further to protect people privacy. Namely, we want to average the gradients BEFORE calling .get(). That way, we won't ever see anyone's exact gradient (thus better protecting their privacy!!!)

But, in order to do this, we need a few more pieces:

- use a pointer to send a Tensor directly to another worker

And in addition, while we're here, we're going to learn about a few more advanced tensor operations as well which will help us both with this example and a few in the future!

In [0]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
x = x.send(alice)

In [0]:
bob._objects

{681755396: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{59232059007: (Wrapper)>[PointerTensor | alice:59232059007 -> bob:681755396]}

In [0]:
y = x + x

In [0]:
y

(Wrapper)>[PointerTensor | me:35076229352 -> alice:14700048988]

In [0]:
bob._objects

{681755396: tensor([1, 2, 3, 4, 5]), 61259427323: tensor([ 2,  4,  6,  8, 10])}

In [0]:
alice._objects

{14700048988: (Wrapper)>[PointerTensor | alice:14700048988 -> bob:61259427323],
 59232059007: (Wrapper)>[PointerTensor | alice:59232059007 -> bob:681755396]}

In [0]:
jon = sy.VirtualWorker(hook, id="jon")

In [0]:
bob.clear_objects()
alice.clear_objects()



<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)
y = th.tensor([1,2,3,4,5]).send(bob).send(jon)

In [0]:
z = x + y

TensorsNotCollocatedException: ignored

In [0]:
x = x.get() # to get the data back
x

(Wrapper)>[PointerTensor | me:59854104348 -> bob:36602545298]

In [0]:
bob._objects

{36602545298: tensor([1, 2, 3, 4, 5]), 89784608003: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{}

In [0]:
x = x.get()
x

tensor([1, 2, 3, 4, 5])

In [0]:
bob._objects

# Lesson: Pointer Chain Operations

In [0]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob)

In [0]:
bob._objects

{36597101211: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{}

In [0]:
x.move(alice)

(Wrapper)>[PointerTensor | me:16851411436 -> alice:16851411436]

In [0]:
x

(Wrapper)>[PointerTensor | me:16851411436 -> alice:16851411436]

In [0]:
bob._objects

{}

In [0]:
alice._objects

{16851411436: tensor([1, 2, 3, 4, 5])}

In [0]:
bob.clear_objects()
alice.clear_objects()

<VirtualWorker id:alice #objects:0>

In [0]:
x = th.tensor([1,2,3,4,5]).send(bob).send(alice)

In [0]:
bob._objects

{81869613150: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{99685627431: (Wrapper)>[PointerTensor | alice:99685627431 -> bob:81869613150]}

In [0]:
x

(Wrapper)>[PointerTensor | me:83688287202 -> alice:99685627431]

In [0]:
x.remote_get() # inplace operation

(Wrapper)>[PointerTensor | me:83688287202 -> alice:99685627431]

In [0]:
bob._objects

{}

In [0]:
alice._objects

{99685627431: tensor([1, 2, 3, 4, 5])}

In [0]:
x.move(bob)

(Wrapper)>[PointerTensor | me:83688287202 -> bob:83688287202]

In [0]:
x

(Wrapper)>[PointerTensor | me:83688287202 -> bob:83688287202]

In [0]:
bob._objects

{83688287202: tensor([1, 2, 3, 4, 5])}

In [0]:
alice._objects

{}

**Exercise 1:**

- Create a toy dataset
- Create a toy linear model
- Train the dataset using Federated Learning, but do not share the gradiant with the main server, instead use the move function to send the gradients to one of the participating workers, aggregate the model, then send the final model to the main server (i.e., local worker).



---


**Exercise 2:**

While exercise 1 illustrates a good example of preseving privacy in FL, we still had to expose the gradients to one of the participating workers. To avoid this limitation, you need to send the gradiants to a TRUSTED thirdparty (trusted aggregator) who will aggregate the models and then send the final model to the server (local worker). In this way, we assure that none of the participating workers can access the aggregated model!

1. create a dataset for each worker (create two)
2. create a model for each worker and train it remotely on each worker
3. send those two models using the *move()* function to a third worker
4. the third workers aggregates the two models (find their mean)
5. send the aggregated model to the main server (local worker) using the *get()* function



---

To set the weights: `model.weight.set_()`



In [1]:
# Exercise 1
import syft as sy
import torch as th
from torch import nn, optim

W0703 00:50:42.332767 140153000220544 secure_random.py:26] Falling back to insecure randomness since the required custom op could not be found for the installed version of TensorFlow. Fix this by compiling custom ops. Missing file was '/usr/local/lib/python3.6/dist-packages/tf_encrypted/operations/secure_random/secure_random_module_tf_1.14.0.so'
W0703 00:50:42.349664 140153000220544 deprecation_wrapper.py:119] From /usr/local/lib/python3.6/dist-packages/tf_encrypted/session.py:26: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.



In [0]:
hook = sy.TorchHook(th)

In [0]:
# create workers
bob = sy.VirtualWorker(hook, id="bob")
alice = sy.VirtualWorker(hook, id="alice")
secureWorker = sy.VirtualWorker(hook, id="secure")

In [4]:
# Make each worker aware of the other workers
bob.add_workers([alice,secureWorker])
alice.add_workers([bob,secureWorker])
secureWorker.add_workers([bob, alice])

W0703 00:50:46.774368 140153000220544 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior
W0703 00:50:46.778596 140153000220544 base.py:628] Worker secure already exists. Replacing old worker which could cause                     unexpected behavior
W0703 00:50:46.781118 140153000220544 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0703 00:50:46.782116 140153000220544 base.py:628] Worker secure already exists. Replacing old worker which could cause                     unexpected behavior
W0703 00:50:46.783060 140153000220544 base.py:628] Worker bob already exists. Replacing old worker which could cause                     unexpected behavior
W0703 00:50:46.784050 140153000220544 base.py:628] Worker alice already exists. Replacing old worker which could cause                     unexpected behavior


<VirtualWorker id:secure #objects:0>

In [0]:
# A Toy Dataset
data = th.tensor([[1.,1],[0,1],[1,0],[0,0]], requires_grad=True)
target =  th.tensor([[1.],[1], [0], [0]], requires_grad=True)

In [0]:
# create local datasets at Bob and Alice
data_bob = data[0:2].send(bob)
target_bob = target[0:2].send(bob)

data_alice = data[2:4].send(alice)
target_alice = target[2:4].send(alice)
datasets = [(data_bob, target_bob), (data_alice, target_alice)]

In [0]:
# create a linear model at local worker

In [0]:
# train the models at alice and bob
# move the models to the third worker
# aggreegate the models
# send the model back to the local worker

In [0]:
#Excercise 2
def train(iterations=1):
      for iter in range(iterations):
        model = nn.Linear(2,1)
        opt_bob = optim.SGD(params=model.parameters(), lr=0.1)
        opt_alice = optim.SGD(params=model.parameters(), lr=0.1)
        opt_bob.zero_grad()
        opt_alice.zero_grad()
        model_bob = model.copy().send(bob)
        model_alice = model.copy().send(alice)
        pred_bob = model_bob(data_bob)
        pred_alice = model_alice(data_alice)
        loss_bob = ((pred_bob - target_bob)**2).mean()
        loss_alice = ((pred_alice - target_alice)**2).mean()
        loss_bob.backward()
        opt_bob.step()
        loss_alice.backward()
        opt_alice.step()
        model_bob.move(secureWorker)
        model_alice.move(secureWorker)
        print(secureWorker._objects)
        w_avg = (model_bob.weight+model_alice.weight)/2
        w_avg_output = w_avg.get()
        print(w_avg_output.data)
  

In [25]:
train()

{47336622589: Parameter containing:
tensor([[-0.2603, -0.1926]], requires_grad=True), 11479238815: Parameter containing:
tensor([-0.4186], requires_grad=True), 38449963365: Parameter containing:
tensor([[-0.2603, -0.1926]], requires_grad=True), 61388077267: Parameter containing:
tensor([-0.4186], requires_grad=True), 10767226419: Parameter containing:
tensor([[0.6527, 0.3346]], requires_grad=True), 36789438257: Parameter containing:
tensor([-0.3585], requires_grad=True), 32722961391: Parameter containing:
tensor([[0.6527, 0.3346]], requires_grad=True), 57967004745: Parameter containing:
tensor([-0.3585], requires_grad=True), 29383478172: Parameter containing:
tensor([[0.1007, 0.5202]], requires_grad=True), 62637870736: Parameter containing:
tensor([0.6973], requires_grad=True), 92818755659: Parameter containing:
tensor([[0.1007, 0.5202]], requires_grad=True), 29512881336: Parameter containing:
tensor([0.6973], requires_grad=True), 55054735144: Parameter containing:
tensor([[-0.4317,  0

In [0]:
#Excercise 1
def train(iterations=1):
      for iter in range(iterations):
        model = nn.Linear(2,1)
        opt_bob = optim.SGD(params=model.parameters(), lr=0.1)
        opt_alice = optim.SGD(params=model.parameters(), lr=0.1)
        opt_bob.zero_grad()
        opt_alice.zero_grad()
        model_bob = model.copy().send(bob)
        model_alice = model.copy().send(alice)
        pred_bob = model_bob(data_bob)
        pred_alice = model_alice(data_alice)
        loss_bob = ((pred_bob - target_bob)**2).mean()
        loss_bob.backward()
        opt_bob.step()
        model_bob.move(alice)
        pred_alice = model_bob(data_alice)
        loss_alice = ((pred_alice - target_alice)**2).mean()
        loss_alice.backward()
        opt_alice.step()
        print(alice._objects)
        model = model_alice.get()
        print(loss_alice.get())

In [31]:
train()

{9798098383: tensor([[1., 0.],
        [0., 0.]], requires_grad=True), 11148199591: tensor([[0.],
        [0.]], requires_grad=True), 71864048233: tensor([[-0.6789],
        [-0.4186]], grad_fn=<AddmmBackward>), 47404783995: tensor(0.3180, grad_fn=<MeanBackward0>), 90544991304: Parameter containing:
tensor([[0.6611, 0.5060]], requires_grad=True), 96093633350: Parameter containing:
tensor([-0.3378], requires_grad=True), 83813601694: tensor([[ 0.3233],
        [-0.3378]], grad_fn=<AddmmBackward>), 18842099108: Parameter containing:
tensor([[-0.1025,  0.4317]], requires_grad=True), 39543944410: Parameter containing:
tensor([0.5431], requires_grad=True), 9117868859: Parameter containing:
tensor([[-0.1025,  0.4317]], requires_grad=True), 81646292803: Parameter containing:
tensor([0.5431], requires_grad=True), 48997152446: tensor([[0.4406],
        [0.5431]], grad_fn=<AddmmBackward>), 94669034706: tensor(0.2446, grad_fn=<MeanBackward0>), 76753967667: Parameter containing:
tensor([[-0.2570, -